### ISSUE TITLE
TX9 核显

### ISSUE THREAD

**Issue by zhudaye1990** [linlinger/hasee-N960Kx-hackintosh#1]
我在年中找淘宝配置EFI，现在可以正常进入系统，但核显是无法驱动的，打上驱动后开机就黑屏，不打驱动就只有7m 因为主板是H570，我的CPU是10700

**Comment by linlinger** [comment]
我稍后会上传EFI，我之前给搞忘记了

**Comment by linlinger** [comment]
镜像已上传。去试试吧
